// components/react/scroll-tips/components/scroll-tips/index.jsx
import React, { Component } from 'react'
import './styles.scss'
const listDefault = new Array(12).fill({
  userAvatarUrl: 'xxx',
  lefttext: 'm***2抽中',
  centre: '88元',
  righttext: '现金'
})

export default class ScrollTips extends Component {
  static defaultProps = {
    visible: false,
    onClose() {},
    type: 0
  }

  timer = null
  state = {
    list: [],
    defaultAvatar: 'xx',
    animateUp: false,
    timer: null,
    visible: false
  }
  constructor(props) {
    super(props)
    this.state.list = listDefault
  }
  render() {
    const { list, animateUp, defaultAvatar, visible } = this.state

    const listItems = list.map(item => (
      <div className="scroll-tips__item" key={item.id}>
        <div
          className="avatar"
          style={{
            backgroundImage: `url(${item.userAvatarUrl || defaultAvatar})`
          }}
        ></div>
        <div>
          {item.lefttext}
          <span style={{ color: '#fffe00' }}>{item.centre}</span>
          {item.righttext}
        </div>
      </div>
    ))
    return (
      <div className="scroll-tips">
        <div className={`${animateUp ? 'animate-up' : ''}`}>{listItems}</div>
      </div>
    )
  }
  show = () => {
    this.setState({ visible: true })
  }
  hidden = () => [this.setState({ visible: false })]
  scrollAnimate = () => {
    const { list } = this.state
    if (list.length <= 1) return
    this.setState({ animateUp: true })
    setTimeout(() => {
      list.push(list[0])
      list.shift()
      const animateUp = false
      this.setState({ list, animateUp })
    }, 600)
  }
  componentWillUnmount() {
    clearInterval(this.timer)
  }
  componentDidMount() {
    this.timer = setInterval(this.scrollAnimate, 2000)
  }
}

// components/vue/scroll-tips/components/scroll-tips/index.vue
<template>
  <div class="scroll-tips" v-if="list && list.length">
    <div class="scroll-tips__item__wrap" :class="{ 'animate-up': animateUp }">
      <div class="scroll-tips__item" v-for="item in list" :key="item.id">
        <div
          class="scroll-tips__item__avatar"
          :style="{ backgroundImage: `url(${item.userAvatarUrl})` }"
        ></div>
        <div>
          {{ item.userName }}刚刚摇到{{
            item.rewardAmount | formatAmount
          }}元奖励金
        </div>
      </div>
    </div>
  </div>
</template>
<style lang="scss" scoped>
@import './styles.scss';
</style>
<script>
import Vue from 'vue'
import Component from 'vue-class-component'

@Component({
  props: {}
})
class ScrollTips extends Vue {
  list = new Array(12).fill({
    userAvatarUrl: '',
    userName: 'xxx',
    rewardAmount: 'xxx'
  })
  defaultAvatar = ''
  animateUp = false
  timer = null

  created() {
    // getWinRewardPrizeUserList(this.drawLotterySecret).then(res => {
    //     res && (this.list = this.initData(res))
    // })
  }

  destroyed() {
    clearInterval(this.timer)
  }

  mounted() {
    this.timer = setInterval(this.scrollAnimate, 2000)
  }

  // initData(res) {
  //   if (!Array.isArray(res)) return []
  //   res.forEach(item => {
  //     if (item.userAvatarUrl) {
  //       item.userAvatarUrl = `${
  //         decodeURIComponent(item.userAvatarUrl).split('@')[0]
  //       }@50w_50h_1e_1c`
  //     } else {
  //       item.userAvatarUrl = this.defaultAvatar
  //     }
  //   })
  //   return res
  // }

  scrollAnimate() {
    if (this.list.length <= 1) return
    this.animateUp = true
    setTimeout(() => {
      this.list.push(this.list[0])
      this.list.shift()
      this.animateUp = false
    }, 600)
  }

  toast(msg) {
    window.Block.trigger('infopop', msg)
  }
}

export default ScrollTips
</script>
